### ISSUE TITLE
3.4.23 breaks when using non-default Rails logger

### ISSUE THREAD

**Issue by jbotelho2-bb** [sass/sass#2214]
After upgrading to from sass 3.4.22 to 3.4.23 today, we saw it breaking on some new code in the gem:

```
NoMethodError: undefined method `log_level' for #<Log4r::Logger:0x007f40eb13a5a0>
/app/vendor/bundle/ruby/2.1.0/gems/sass-3.4.23/lib/sass/logger/delayed.rb:26:in `initialize'
/app/vendor/bundle/ruby/2.1.0/gems/sass-3.4.23/lib/sass/logger/delayed.rb:17:in `new'
/app/vendor/bundle/ruby/2.1.0/gems/sass-3.4.23/lib/sass/logger/delayed.rb:17:in `install!'
```

It seems to assume that the logger supports all the methods that a standard ruby logger supports (such as `#log_level`), which may be reasonable, but isn't always the case. In our situation, the sass-rails gem sets `Sass.logger` to be the default rails logger, which ends up being an instance of `Log4r:Logger`.

**Comment by nex3** [comment]
This seems like an issue with sass-rails. The `Sass.logger` attribute only expects an instance of `Sass::Logger::Base`; if sass-rails is passing in something else, it has a responsibility to make sure it's API-compatible.

**Comment by shayneoAtNorwood** [comment]
Note for people still having this issue

gem 'sass', '3.4.22'

Will fix it until the sass (or sass-rails I suppose?) people fix it. If its sass-rails at fault, the issue is independent of version of sass-rails.

**Comment by jbotelho2-bb** [comment]
To clarify, this issue ended up not being caused by sass or sass-rails; we had another library that was monkey-patching the logger method on Object. Sorry for any confusion.

**Comment by msumit** [comment]
I'm too getting a similar issue while precompiling assets

> NoMethodError: undefined method `log_level' for #<ActiveSupport::Logger:0x007f99d13ade38>
> /Users/sumitm/.rvm/gems/ruby-2.1.6/gems/sass-3.7.2/lib/sass/logger/delayed.rb:26:in `initialize'
> /Users/sumitm/.rvm/gems/ruby-2.1.6/gems/sass-3.7.2/lib/sass/logger/delayed.rb:17:in `new'
> /Users/sumitm/.rvm/gems/ruby-2.1.6/gems/sass-3.7.2/lib/sass/logger/delayed.rb:17:in `install!'

Below are the versions I'm using:

ruby: 2.1.6
rails: 4.2.11
sass-rails: 5.0.7
sass: 3.7.2

**Comment by nex3** [comment]
@msumit It looks like you're still using Ruby Sass. Ruby Sass has reached [end of life](https://sass-lang.com/blog/posts/7828841-ruby-sass-is-unsupported), and is no longer supported. Please switch to another implementation as soon as possible to ensure that you'll remain up-to-date with the latest features and CSS support.
