### ISSUE TITLE
unable to set load-path with 3.4.0.rc.1 

### ISSUE THREAD

**Issue by benib** [sass/sass#1314]
When I set a load-path with `--load-path` I get the following error with sass 3.4.0.rc.1:

```
~/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.4.0.rc.1/lib/sass/exec/sass_scss.rb:72:in `block in common_options': undefined method `<<' for nil:NilClass (NoMethodError)
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `call'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1359:in `block in parse_in_order'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `catch'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1346:in `parse_in_order'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1340:in `order!'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1432:in `permute!'
    from ~/.rbenv/versions/2.1.1/lib/ruby/2.1.0/optparse.rb:1454:in `parse!'
    from ~/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.4.0.rc.1/lib/sass/exec/base.rb:38:in `parse'
    from ~/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.4.0.rc.1/lib/sass/exec/base.rb:19:in `parse!'
    from ~/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.4.0.rc.1/bin/sass:13:in `<top (required)>'
    from ~/.rbenv/versions/2.1.1/bin/sass:23:in `load'
    from ~/.rbenv/versions/2.1.1/bin/sass:23:in `<main>'
```

This works with sass 3.3.10. If I can somehow provide more information, please let me know.

btw, thanks for `@error`

**Comment by hail2u** [comment]
Same here. But setting `SASS_PATH=.` in shell environment variable resolves this issue on my machine.

**Comment by westlywright** [comment]
Getting the same issue here with the same release
