### ISSUE TITLE
Regression with 3.4.6: undefined method `specificity' 

### ISSUE THREAD

**Issue by bradvogel** [sass/sass#1476]
Hi, I just upgraded from sass 3.4.5 to 3.4.6 and am now getting the error when running `compass compile`:

```
    error client/sass/styles.scss (/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for [:not(:last-child)]:Array)
```

I can confirm it's a regression with 3.4.6 because when I downgraded to 3.4.5 it worked fine with the same sass.

Here are my gem versions:

```
brad: emailer-app (master) gem list

*** LOCAL GEMS ***

animation (0.1.alpha.3)
bigdecimal (1.2.0)
CFPropertyList (2.2.0)
chunky_png (1.3.1)
compass (1.0.1)
compass-core (1.0.1)
compass-flexbox (1.1.3)
compass-import-once (1.0.5)
ffi (1.9.5)
fssm (0.2.10)
io-console (0.4.2)
json (1.7.7)
libxml-ruby (2.6.0)
minitest (4.3.2)
multi_json (1.10.1)
nokogiri (1.5.6)
psych (2.0.0)
rake (0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdoc (4.0.0)
sass (3.4.6)
sqlite3 (1.3.7)
test-unit (2.0.0.0)
```

**Comment by nex3** [comment]
Can you provide a small example of code that reproduces this error?

**Comment by robi-wan** [comment]
Same error here:

```
>sass  --update src:build --load-path . --style compressed  --trace
C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:96:in `_specificity': undefined method `specificity' for [:not(.expandable-group)]:Array (NoMethodError)
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:94:in `each'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:86:in `specificity'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:96:in `_specificity'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:94:in `each'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/abstract_sequence.rb:86:in `specificity'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:550:in `trim'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/staleness_checker.rb:65:in `map'
        from C:/development/lang/ruby187/lib/ruby/1.8/set.rb:195:in `each'
        from C:/development/lang/ruby187/lib/ruby/1.8/set.rb:195:in `each_key'
        from C:/development/lang/ruby187/lib/ruby/1.8/set.rb:195:in `each'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:549:in `map'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:549:in `trim'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:544:in `reject'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:544:in `trim'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/staleness_checker.rb:65:in `each_with_index'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:543:in `each'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:543:in `each_with_index'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:543:in `trim'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:123:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/simple_sequence.rb:192:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/simple_sequence.rb:190:in `map!'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/simple_sequence.rb:190:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:112:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:110:in `map'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/sequence.rb:110:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/comma_sequence.rb:71:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/comma_sequence.rb:70:in `map'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/selector/comma_sequence.rb:70:in `do_extend'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:44:in `visit_rule'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:36:in `send'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:36:in `visit'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:28:in `visit'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:52:in `visit_children'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:52:in `map'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:52:in `visit_children'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:37:in `visit_children'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/base.rb:38:in `visit'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:28:in `visit'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:15:in `send'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/visitors/extend.rb:15:in `visit'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/root_node.rb:39:in `css_tree'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/engine.rb:368:in `_render_with_sourcemap'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/engine.rb:285:in `render_with_sourcemap'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/compiler.rb:489:in `update_stylesheet'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/compiler.rb:215:in `update_stylesheets'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/compiler.rb:209:in `each'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/plugin.rb:82:in `update_stylesheets'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/exec/sass_scss.rb:350:in `watch_or_update'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/exec/sass_scss.rb:50:in `process_result'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/exec/base.rb:52:in `parse'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/../lib/sass/exec/base.rb:19:in `parse!'
        from C:/development/lang/ruby187/lib/ruby/gems/1.8/gems/sass-3.4.6/bin/sass:13
        from C:/development/lang/ruby187/bin/sass:23:in `load'
        from C:/development/lang/ruby187/bin/sass:23
```

No sample but maybe the stacktrace helps.
Environment: Windows Server 2003, Ruby 1.8.7
Happens after update to sass 3.4.6; error did not occur in sass 3.4.5

**Comment by AnnikaNissen** [comment]
Same Problem here:

```
directory target/css_js_temp/external_navi
    error src/main/webapp/app/sass/external_navi_combined.scss (/var/lib/gems/1.9.1/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for [:not([controls])]:Array)
```

Here is a code example:
in external_navi_combined.scss:

``` scss
#pageHeader {
      @import "../../globals/sass/scss/normalize.scss/normalize";
}
```

in _normalize.scss

``` scss
audio:not([controls]) {
      display: none;
      height: 0;
}
```

Sass-Version is 3.4.6. Ruby is ruby 1.9.3p0 (2011-10-30 revision 33570) [x86_64-linux]
With Sass-Version 3.4.5 this code worked fine.

**Comment by yanneves** [comment]
Also getting this error in build, no problems in v3.4.5.

`NoMethodError: undefined method 'specificity' for [:not(old)]:Array`

Example:

```
input[type=radio]:not(old){
    width   : 0px;
    margin  : 0;
    padding : 0;
    opacity : 0;
    &:checked{
        background: blue;
    }
}
```

**Comment by Anahkiasen** [comment]
Getting this too

**Comment by mgol** [comment]
I got a similar error:

```
NoMethodError: undefined method `unify' for [:not(.object-thumbnail)]:Array
```

It worked fine in 3.4.5.

EDIT: my minimal example:

``` scss
.ellipsis {
    top: 0;
}

a {
    div:not(.object-thumbnail) {
        @extend .ellipsis;
    }
}
```

The error message on that example:

```
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:226:in `block in unify': undefined method `unify' for [:not(.object-thumbnail)]:Array (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:224:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:224:in `inject'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:224:in `unify'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:181:in `block in do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:174:in `map!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/simple_sequence.rb:174:in `do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/sequence.rb:112:in `block in do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/sequence.rb:110:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/sequence.rb:110:in `do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:71:in `block in do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `do_extend'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:44:in `visit_rule'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:36:in `visit'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `map'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `visit_children'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:37:in `visit_children'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:38:in `visit'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:15:in `visit'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/root_node.rb:39:in `css_tree'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/tree/root_node.rb:29:in `render_with_sourcemap'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/engine.rb:368:in `_render_with_sourcemap'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/engine.rb:285:in `render_with_sourcemap'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:396:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:62:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/exec/base.rb:52:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/lib/sass/exec/base.rb:19:in `parse!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.6/bin/sass:13:in `<top (required)>'
    from /usr/bin/sass:23:in `load'
    from /usr/bin/sass:23:in `<main>'
```

**Comment by voku** [comment]
Sass 3.4.6  -> error scss/app.scss (d:/xampp/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method`
specificity' for [:not(.button)]:Array)

**Comment by ryanlntn** [comment]
I'm experiencing the same issue. Reverting to version `3.4.5` resolves it. The code in question:

``` scss
input:not([type=checkbox]) {
  width: 100%;
}
```

**Comment by tripwarneke** [comment]
Perhaps the fix to "Parent selectors now work in selector pseudoclasses (for example, :not(&))." broke something with the specificity call in sass 3.4.6. I ran into this myself with a similar bit of sass as ryanlntn that was working before. Moving back to 3.4.5 fixes the problem.

Partial stacktrace on the error (I was running rake assets:precompile):

```
NoMethodError: undefined method `specificity' for [:not([type='checkbox'])]:Array
  (in /app/assets/stylesheets/sign-in.scss)
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `each'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:86:in `specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `each'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:94:in `_specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:86:in `specificity'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:550:in `block (3 levels) in trim'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:549:in `map'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:549:in `block (2 levels) in trim'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:544:in `reject'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:544:in `block in trim'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `each'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `each_with_index'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:543:in `trim'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/sequence.rb:123:in `do_extend'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:71:in `block in do_extend'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `map'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/selector/comma_sequence.rb:70:in `do_extend'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:44:in `visit_rule'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:37:in `visit_children'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/base.rb:38:in `visit'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:28:in `visit'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/visitors/extend.rb:15:in `visit'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/root_node.rb:39:in `css_tree'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/tree/root_node.rb:20:in `render'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-3.4.6/lib/sass/engine.rb:268:in `render'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sass-rails-3.2.5/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
/Users/twarneke/.rvm/gems/ruby-1.9.3-p484@client-dashboard/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
```

**Comment by andrewjtait** [comment]
From what I can see it is [this commit](https://github.com/sass/sass/commit/c717726c4307899bec87482673bfb7fb6fe1f509) which has introduced the bug. The fact that it now [returns an Array](https://github.com/sass/sass/blob/c717726c4307899bec87482673bfb7fb6fe1f509/lib/sass/selector/pseudo.rb#L93-L97) is not being handled in [this method](https://github.com/sass/sass/blob/stable/lib/sass/selector/abstract_sequence.rb#L96) - it is expecting an instance of the `Sass::Selector::Pseudo` class, but is instead now given an `Array` containing the instance.

**Comment by jorgecasar** [comment]
The same happens trying to compile ionic framework

**Comment by apreg** [comment]
Same here but downgrade solved it.

**Comment by trevorpowell** [comment]
Getting the same:

```
error styles/sass/main_light.scss (/usr/local/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for [:not(:last-child)]:Array)
```

Compilation failed in 1 files.

**Comment by nvanheuverzwijn** [comment]
Same here
`NoMethodError: undefined method 'specificity' for [:not(.checked)]:Array`

**Comment by brunopgalvao** [comment]
`li:not(:last-child) { margin-right: 20px; }`

Cannot downgrade :(

```
sass-rails (= 4.0.3) ruby depends on
  sprockets-rails (~> 2.0) ruby

rails (= 4.2.0.beta1) ruby depends on
  sprockets-rails (3.0.0.beta1)
```

**Comment by bolderbrooklyn** [comment]
@brunopgalvao, you need to downgrade Sass, not `sass-rails`. Your `Gemfile` should have:

``` ruby
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'sass', '3.4.5'
```

Then run `bundle update sass`. Once this is fixed and a new version is released, remove the `gem 'sass'` line and run `bundle update sass` again.

**Comment by rpedroni** [comment]
Like others commented, downgrading to sass 3.4.5 resolved the issue for me, though I did this simply removing and adding the sass gem globally

```
sudo gem uninstall sass
sudo gem install sass -v 3.4.5
```

**Comment by jltemple** [comment]
Also having the same problem, when working with Foundation.
Seems like that update "Parent selectors now work in selector pseudoclasses (for example, :not(&))." caused some trouble.
Just downgraded to 3.4.5 as @rpedroni said.

**Comment by victor-guoyu** [comment]
Having same problem. Resolved using Sass 3.4.5.

**Comment by patrick-wc** [comment]
Still getting this error too. Just ran gem update sass, it said nothing to update.

I downgraded to 3.4.5 `gem install sass -v 3.4.5` and now it works fine.

**Comment by abepetrillo** [comment]
+1. Also reproduced this issue. Thanks for the work around @bradvogel

**Comment by tmazeika** [comment]
Same issue.

**Comment by suncat3** [comment]
Same issue today.  Thank you for the work around. It saved me time/headache.

**Comment by Anahkiasen** [comment]
That's because 3.4.7 [isn't out yet](http://rubygems.org/gems/sass).

**Comment by bowenliang123** [comment]
i got the same issue.

**Comment by erindru** [comment]
I have this issue too, and can confirm that downgrading to 3.4.5 works.

**Comment by jamonholmgren** [comment]
Good thing for the unsubscribe button...

**Comment by jasonfutch** [comment]
+1

**Comment by markshust** [comment]
Same issue, downgraded to 3.4.5 to resolve.

**Comment by hotmeteor** [comment]
This has also been fixed in [3.4.7](https://github.com/sass/sass/commit/a128adaaf789310b12c64b8e7675b36fb1bc6462)

**Comment by facundofarias** [comment]
Thanks :+1: (Using Sass 3.4.16)

**Comment by Sigma-90** [comment]
Not sure if any recent changes caused this bug to reappear of if it can have multiple causes and only one of them has been fixed with the 3.4.7 update, but the fact of the matter is that the server I'm currently working on is running Sass 3.4.18 and I get this very same error, so I can't define any rules that contain a :not-selector. Very inconvenient.

**Comment by riazek** [comment]
I'm Getting this error

my sass version is 3.4.5

 error styles-ie8.scss (/usr/lib/ruby/vendor_ruby/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method`specificity' for [:not(.button)]:Array)
    error styles.scss (/usr/lib/ruby/vendor_ruby/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method`specificity' for [:not(.block-layered-nav)]:Array)

**Comment by mgol** [comment]
@riazek Your version is extremely out of date. Please update & check again.

**Comment by riazek** [comment]
hi @mzgol ,
 i updated sass to 3.4.18 still getting the same error :(

**Comment by nex3** [comment]
@riazek Please post the full 3.4.18 stack trace for the error you're seeing.

**Comment by robme** [comment]
This bug still exists, I had to downgrade from 3.7.4 to 3.4.5. Any version newer than 3.4.5 has this error about specificity.

**Comment by nex3** [comment]
@robme [Ruby Sass is no longer maintained](http://sass.logdown.com/posts/7828841-ruby-sass-is-unsupported). Please upgrade to a more up-to-date Sass implementation.
