### ISSUE TITLE
Trouble with 3.3 and --watch

### ISSUE THREAD

**Issue by fitzryland** [sass/sass#1151]
regular ole'

```
sass main.scss:main.css
```

works just fine, but the watch flag isn't working out well for me.

```
$ sass --trace --watch main.scss:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
/Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:327:in `listen_to': undefined method `thread' for #<Listen::Listener:0x007ff1513d3a70> (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:294:in `watch'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin.rb:108:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:509:in `watch_or_update'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:346:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:43:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:22:in `parse!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/bin/sass:13:in `<top (required)>'
    from /usr/bin/sass:23:in `load'
    from /usr/bin/sass:23:in `<main>'
```

I would love to know if this is a bug or if I'm just being a dummy. Either way, Google has yielded no conclusions for me.

**Comment by magnetikonline** [comment]
I'm getting major --watch issues with Ubuntu 12.04LTS, it's just not working at all, does an initial compile but doesn't see file changes to re-compile. Was working fine with 3.3.0RC2 (as does if I roll back), but as of 3.3.0RC5 it's no longer working, along with the 3.3.0 final.

Running like so:

sass --line-numbers --scss --style expanded --sourcemap --watch "WATCH_DIR"

Ubuntu 12.04LTS with Ruby 1.8.7.

**Comment by fitzryland** [comment]
I should mention I am on the latest version of OSX

**Comment by nex3** [comment]
What do you get if you run `gem list listen`?

**Comment by TundraTech** [comment]
I have same problem here:

OSX mavericks, 

sass 3.3.0
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
listen 2.7.0

FIXES TRIED::

-rolling back to every version of listen all the way to 1.0, all do not work.
-also tried rolling back rb-fsevent to various versions to no avail.
-uninstalling/reinstalling all gems
-running all gems through rails 2.1.1 with rvm

Reverting back to media mark, all problems are solved, regardless of listen version used.

---------========= HERE IS A TEMPORARY FIX =========---------

listen v.2.4.1 will at least COMPILE 3.0.0, so uninstall all versions except that one

sudo gem uninstall listen

keep doing this till all versions are gone then :

sudo gem install listen -v 2.4.1

after install is complete, open and close terminal and copy/paste then ADJUST THE PATHS to your own working directories:

while :; do sass /wwwroot/sass/_whatever.scss:/wwwroot/css/whatever.css  --precision 12  --style compact; sleep 5; done

That command will force a complie every 5 seconds, you can modify the sleep value to whatever you feel comfortable with. 

Its ugly but at least you can get rolling with 3.3 and maps _cough_ i mean arrays _cough_;

**Comment by magnetikonline** [comment]
As for me, here are the details of what I'm running.

```
$ uname -a
Linux magnetikdev 3.2.0-60-generic-pae #91-Ubuntu SMP Wed Feb 19 04:14:56 UTC 2014 i686 i686 i386 GNU/Linux

$ ruby --version
ruby 1.8.7 (2013-06-27 MBARI 8/0x8770 on patchlevel 375) [i686-linux], MBARI 0x8770, Ruby Enterprise Edition 2012.02

$ gem list

*** LOCAL GEMS ***

ffi (1.9.3)
listen (1.1.6)
rake (10.1.1)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.2)
sass (3.3.0.rc.2)
sass-globbing (1.1.0)
```

Note I am currently running 3.3.0.rc.2 which is working great, the other week upgrading to rc.5 broke `--watch`, figured it would be fixed for the final, but it's still broken. So something between rc.2 -> rc.5 has broken this behaviour.

The first run of sass will build the project, but touching/saving a file after this point does not re-envoke the compiler.

**Comment by samuelbran** [comment]
Same problem here, just upgraded from 3.3.0.rc.4 to 3.3.0 today.

<pre></code>$ sass --sourcemap --watch --trace sass/style.sass:style.css --style expanded
>>> Sass is watching for changes. Press Ctrl-C to stop.
/Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:327:in `listen_to': undefined method `thread' for #<Listen::Listener:0x007fca2b601330> (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:294:in `watch'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/plugin.rb:108:in `method_missing'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:509:in `watch_or_update'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:346:in `process_result'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:43:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/lib/sass/exec.rb:22:in `parse!'
        from /Library/Ruby/Gems/2.0.0/gems/sass-3.3.0/bin/sass:13:in `<top (required)>'
        from /usr/bin/sass:23:in `load'
        from /usr/bin/sass:23:in `<main>'</code></pre>

<pre><code>gem list listen
*** LOCAL GEMS ***
listen (2.7.0, 2.4.1, 1.3.1, 1.1.6)</code></pre>

**Comment by fhars** [comment]
Looks like 69308c22b8518d65dee0db36241df423284e85f8 isn't doing what it should. I read that as trying to install a version of listen < 2.5 for Ruby 1.9.3 and up, yet I ended up with:

```
$ gem list listen

*** LOCAL GEMS ***

listen (2.7.0)
```

after installing sass 3.3.0, on a system with almost no other intalled ruby stuff:

```
$ dpkg -l *ruby* | grep '^i'

ii  libruby1.9.1                                   1.9.3.194-8.1ubuntu1.2                     amd64        Libraries necessary to run Ruby 1.9.1
ii  ruby                                           4.9                                        all          Interpreter of object-oriented scripting language Ruby (default version)
ii  ruby1.9.1                                      1.9.3.194-8.1ubuntu1.2                     amd64        Interpreter of object-oriented scripting language Ruby
ii  ruby1.9.1-dev                                  1.9.3.194-8.1ubuntu1.2                     amd64        Header files for compiling extension modules for the Ruby 1.9.1

$ gem list

*** LOCAL GEMS ***

celluloid (0.15.2)
celluloid-io (0.15.0)
ffi (1.9.3)
listen (2.7.0)
nio4r (1.0.0)
rake (10.1.1)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
sass (3.3.0)
timers (1.1.0)
```

**Comment by fhars** [comment]
A further data point:

```
gem uninstall listen
gem install listen --version '2.4.1'
```

enabled `sass --watch` for me.

**Comment by varemenos** [comment]
Same here

``` bash
sass --watch assets/css/style.scss:assets/css/style.css        

>>> Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: ^Cundefined method 'thread' for #<Listen::Listener:0xa307b40>
  Use --trace for backtrace.
^C/usr/lib/ruby/1.9.1/thread.rb:71:in 'sleep': Interrupt
    from /usr/lib/ruby/1.9.1/thread.rb:71:in 'wait'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:37:in 'block in join'
    from <internal:prelude>:10:in 'synchronize'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/thread_handle.rb:37:in 'join'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid/actor.rb:129:in 'join'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:162:in 'block (2 levels) in shutdown'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:160:in 'each'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:160:in 'block in shutdown'
    from /usr/lib/ruby/1.9.1/timeout.rb:68:in 'timeout'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:144:in 'shutdown'
    from /var/lib/gems/1.9.1/gems/celluloid-0.15.2/lib/celluloid.rb:131:in 'block in register_shutdown'
```

``` bash
uname -a
Linux home 3.11.0-17-generic #31-Ubuntu SMP Mon Feb 3 21:53:31 UTC 2014 i686 i686 i686 GNU/Linux

sass -v
Sass 3.3.0 (Maptastic Maple)

ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [i686-linux]

gem list listen                                                

*** LOCAL GEMS ***

listen (2.7.0, 2.5.0, 2.4.1)
```

**Comment by tomturton** [comment]
When I ran sass -w after upgrading sass 3.3.0, it didn't compile either. The message I got was:

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError:
```

Using TundraTech's listen downgrade fix worked for me.

OSX 10.9.2
Sass 3.3.0
ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]

**Comment by samuelbran** [comment]
Just remove Listen 2.7.0, I'm using v2.4.1 and all is back to normal.

**Comment by dorward** [comment]
The approach that worked for me (steps 1 and 2 might be optional):
1. Remove the existing versions of listen: `sudo gem uninstall listen`  (Pick All versions if prompted)
2. Remove the existing versions of sass: `sudo gem uninstall listen`  (Pick All versions if prompted)
3. Install the correct versions of sass and listen: `sudo gem install listen:2.4.1 sass:3.3`
4. Uninstall the wrong version of listen: `sudo gem uninstall listen`  (Pick the 2.7 version)

**Comment by laurensvanpoucke** [comment]
gem uninstall listen --version 2.7.0
gem install listen --version 2.4.1
Did the trick here!

**Comment by slothelle** [comment]
Listen was removed as a Sass dependency with the version change, but I don't think they expected this particular side effect. 

From the [Changelog](http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#smaller_improvements):

> listen is no longer bundled with Sass, nor is it a standard RubyGems dependency. Instead, it’s automatically installed along with Sass in order to ensure that the user ends up with a version of Listen that works with their local Ruby version.

As everyone else indicated above `--watch` works fine with Listen v2.4.1.
