### ISSUE TITLE
@at-root issue

### ISSUE THREAD

**Issue by airen** [sass/sass#1111]
Hello everyone，I encountered a problem with `@at-root`. I have this code:

```
@charset "UTF-8";

.block {
    color: green;
    @at-root {
        #{&}__e{
            color: blue;
        }
        #{&}--f{
            color:green;
        }
    }
}
```

But the compile time error

```
>>> Sass is watching for changes. Press Ctrl-C to stop.
      error hotel.scss (Line 5: Invalid CSS after "             #{": expected ex
pression (e.g. 1px, bold), was "&}__e{")
NoMethodError: undefined method `to' for Listen:Module
  Use --trace for backtrace.
```

My operating environment is as follows：

```
ruby -v
ruby 2.0.0p353 (2013-11-22) [i386-mingw32]

sass -v
Sass 3.3.0.rc.3 (Maptastic Maple)
```

Why is this ? How do I solve this problem ?

**Comment by airen** [comment]
###Listen not working with sass-3.3.0.rc.3 - Undfined Method

I had updated Sass　to `Sass 3.3.0.rc.3 (Maptastic Maple)`,But I can not use `-watch` command：

```
$ sass --watch  test.scss:test.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: undefined method `to' for Listen:Module
  Use --trace for backtrace.
```

and i use the command:

```
 sass --trace --watch test.scss:test.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
/Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/plugin/compiler.rb:306:in `create_listener': undefined method `to' for Listen:Module (NoMethodError)
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/plugin/compiler.rb:233:in `watch'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/plugin.rb:108:in `method_missing'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/exec.rb:509:in `watch_or_update'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/exec.rb:346:in `process_result'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/exec.rb:43:in `parse'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/lib/sass/exec.rb:22:in `parse!'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/gems/sass-3.3.0.rc.3/bin/sass:13:in `<top (required)>'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/bin/sass:23:in `load'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/bin/sass:23:in `<main>'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/airen/.rvm/gems/ruby-1.9.3-p392/bin/ruby_noexec_wrapper:14:in `<main>'
```

my ruby and sass version:

```
$ ruby -v
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.4.0]
$ sass -v
Sass 3.3.0.rc.3 (Maptastic Maple)
```

here's the gem list output

```
*** LOCAL GEMS ***

bigdecimal (1.1.0)
bourbon (3.1.8)
bundler (1.3.5)
bundler-unload (1.0.1)
celluloid (0.15.2)
chunky_png (1.2.8)
classifier (1.3.3)
colorator (0.1)
colorize (0.5.8)
commander (4.1.3)
compass (0.12.2)
devkit (0.1.0)
directory_watcher (1.4.1)
fast-stemmer (1.0.2)
ffi (1.9.3)
fssm (0.2.10)
highline (1.6.19)
io-console (0.3)
jekyll (1.0.3)
json (1.5.5)
kramdown (1.1.0, 1.0.2)
liquid (2.5.0)
listen (2.4.1, 1.1.6, 0.7.3)
maruku (0.6.1)
minitest (2.5.1)
posix-spawn (0.3.6)
pygments.rb (0.5.1)
rake (10.1.0, 0.9.2.2)
rb-fsevent (0.9.3)
rb-inotify (0.9.2)
rb-kqueue (0.2.0)
rdiscount (2.1.6)
rdoc (3.9.5)
rubygems-bundler (1.2.2)
rvm (1.11.3.8)
safe_yaml (0.7.1)
sass (3.3.0.rc.3, 3.3.0.rc.2, 3.3.0.alpha.201, 3.2.9)
syntax (1.0.0)
thor (0.18.1)
timers (1.1.0)
yajl-ruby (1.1.0)
```

**Comment by nex3** [comment]
Please post separate bug reports in separate GitHub issues.

> Hello everyone，I encountered a problem with `@at-root`.

Between 3.3.0.rc.2 and 3.3.0.rc.3, we removed support for using `&` in SassScript. For the full justification, you can read [this gist](https://gist.github.com/nex3/8050187). You can write your code like this, though:

``` scss
@charset "UTF-8";

.block {
    color: green;
    &__e{
        color: blue;
    }
    &--f{
       color:green;
    }
}
```

> Listen not working with sass-3.3.0.rc.3 - Undfined Method

This is a duplicate of #1110.
